import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getLocale } from "@/i18n/server";
import { LocaleProvider } from "@/hooks/locale-provider";
import ChangeLocale from "@/components/ChangeLanguages";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = getLocale();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <LocaleProvider value={locale}>
          <Header />
          <main className="min-h-svh flex justify-center items-center">
            {children}
          </main>
        </LocaleProvider>
      </body>
    </html>
  );
}
